### ISSUE TITLE
Multi-class segmentation

### ISSUE THREAD

**Issue by xiaona123456** [loic-lb/Unsupervised-Nuclei-Segmentation-using-Spatial-Organization-Priors#2]
Thank you for your excellent work, can this network do multi-category segmentation?

**Comment by loic-lb** [comment]
Hello,

Thank you very much for your interest in our work. It is indeed an interesting question. 

I would say that the method would work for multi-category segmentation if you can provide as reference objects with very distinct shapes (for instance lymphocytes are much smaller than tumoral cells), or if you can separate them in advance with a simple method (for instance stain deconvolution to separate the different stainings and then perform nuclei detection on each channel separately).
